"""add google oauth fields to tbl_users

Revision ID: e5f8a1c3d7b2
Revises: c4d5e6f7a8b9
Create Date: 2026-09-25 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e5f8a1c3d7b2"
down_revision = "c4d5e6f7a8b9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tbl_users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("google_id", sa.String(length=255), nullable=True))
        batch_op.add_column(
            sa.Column("auth_provider", sa.String(length=20), nullable=False, server_default="local")
        )
        batch_op.create_unique_constraint("uq_tbl_users_google_id", ["google_id"])
        batch_op.alter_column(
            "password_hash", existing_type=sa.String(length=255), nullable=True
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("tbl_users", schema=None) as batch_op:
        batch_op.alter_column(
            "password_hash", existing_type=sa.String(length=255), nullable=False
        )
        batch_op.drop_constraint("uq_tbl_users_google_id", type_="unique")
        batch_op.drop_column("auth_provider")
        batch_op.drop_column("google_id")
    # ### end Alembic commands ###
